- name: Set up passwordless SSH
  hosts: all
  tasks:
    - name: Copy SSH public key
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
