- name: Launch an EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Use AWS credentials to launch EC2
      amazon.aws.ec2_instance:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: us-east-1
        instance_type: t2.micro
        image_id: ami-0c55b159cbfafe1f0  # Example AMI ID
        name: MyTestInstance
        state: present