---
- name: Install and configure Apache
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a custom HTML page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome to Ansible!</title></head>
          <body>
          <h1>Hello World from Ansible Playbook</h1>
          </body>
          </html>
